import { Inter } from "next/font/google";
import "./globals.css";
import { Podcast } from "lucide-react";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <main class="content-grid relative">
    <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
