import { Inter } from "next/font/google";
import "./globals.css";
import { Podcast } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
      <main class="content-grid">
      <header className="full h-[100px] flex items-center text-white bg-[#0E141A]">
        <div className="breakout flex justify-between"> 
        <span>IMAGE</span>
        <div>
          <button className="border border-gray-600 border-opacity-50 py-3 px-8">Logga In</button>
        
        </div>
        </div>
      <nav className="breakout flex justify-between items-center ">
            <ul className="flex gap-4">
              <li className="text-[#53616D] uppercase py-4 px-8">Start</li>
              <li className="text-[#53616D] uppercase py-4 px-8">Om oss</li>
              <li className="text-[#53616D] uppercase py-4 px-8">Spelare</li>
              <li className="text-[#53616D] uppercase py-4 px-8">Kontakt</li>
            </ul>
            <button className="flex gap-2 text-yellow-300"><Podcast /> PODCAST</button>
          </nav> 
        </header>
        {children}
       </main>
        </body>
    </html>
  );
}
